# Generated by Django 5.2 on 2026-02-23 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('expert', models.CharField(help_text='Qisqa tavsif yoki ekspert fikri', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_year', models.PositiveSmallIntegerField(help_text='Masalan: 2023')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'epub'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('category', models.ManyToManyField(related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
